encoding: utf-8

excerpt_separator: <!--more-->

markdown: kramdown

kramdown:
  auto_ids: true

defaults:
  -
    scope:
      path: ""
    values:
      metaTitle: "Codelamp v3 : Blog"
      layout: default